title: Proyectos de Cómic - Dani
description: Ilustrador profesional con experiencia en cómic y diseño de personajes.
baseurl: ""         # Déjalo vacío para sitio usuario.github.io
url: "https://danifromdani.github.io"
theme: minima
